name: GH pages
on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn

      - name: Deploy app
        run: yarn build

      - name: Upload app as artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v1